apiVersion: v1
kind: Secret
metadata:
  name: honeycomb-example
type: Opaque
stringData:
  url: https://api.honeycomb.io/1/markers/TestViaCurl
  headers: >
      {
        "X-Honeycomb-Team": "YOUR_API_KEY"
      }
  body: >
    {
      "type": "scaling",
      "start_time": "_time_",
      "message": "_message_"
    }
